spring.application.name=DEUapp

aws.s3.bucket-name=deu-poc-bucket-madinenipavan
aws.access-key-id=AKIA5ZMGIZVUI5RWP2J6
aws.secret-access-key=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
aws.region=ap-south-1