spring.application.name=fileintakeservice
aws.s3.bucket-name=sqs-postgresql-bucket
aws.access-key-id=AKIA5ZMGIZVULXQ4POXM
aws.secret-access-key=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
aws.region=us-east-1
