spring.application.name=fileintakeservice
aws.s3.bucket-name=sqs-postgresql-bucket
aws.access-key-id=AKIA5ZMGIZVUI5RWP2J6
aws.secret-access-key=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
aws.region=us-east-1